#' @importFrom datacheckr check_flag
#' @importFrom devtools install_github
#' @importFrom doParallel registerDoParallel
#' @importFrom foreach foreach
#' @importFrom ggrepel geom_label_repel
#' @importFrom jmbr is.jmb_model
#' @importFrom knitr knit
#' @importFrom markdown renderMarkdown
#' @importFrom magrittr %<>%
#' @importFrom newdata new_data
#' @importFrom plyr ddply
#' @importFrom poisdata read_hobo_csv
#' @importFrom poisix cleanup_date
#' @importFrom poisplot theme_Poisson
#' @importFrom poisspatial ps_nearest
#' @importFrom poissqlite ps_blob_file
#' @importFrom poisutils ps_error
#' @importFrom reshape2 melt
#' @importFrom rmarkdown pdf_document
#' @importFrom RSQLite dbGetQuery
#' @importFrom scales percent
#' @importFrom smbr is.smb_model
#' @importFrom subfoldr save_plot
#' @importFrom tidyverse tidyverse_packages
#' @importFrom tmbr is.tmb_model
NULL
