#' @importFrom abind abind
#' @importFrom assertthat is.number
#' @importFrom assertr verify
#' @importFrom datacheckr check_flag
#' @importFrom devtools install_github
#' @importFrom doParallel registerDoParallel
#' @importFrom forcats as_factor
#' @importFrom foreach foreach
#' @importFrom ggrepel geom_label_repel
#' @importFrom jmbr is.jmb_model
#' @importFrom knitr knit
#' @importFrom kootqlt download_qlt_data
#' @importFrom lubridate date
#' @importFrom magrittr %<>% %>%
#' @importFrom markdown renderMarkdown
#' @importFrom newdata new_data
#' @importFrom plyr ddply
#' @importFrom poisix cleanup_date
#' @importFrom poismap latlong2eastnorth
#' @importFrom poisplot theme_Poisson
#' @importFrom poisutils read_hobo_csv
#' @importFrom readxl read_excel
#' @importFrom reshape2 melt
#' @importFrom rmarkdown pdf_document
#' @importFrom RSQLite dbGetQuery
#' @importFrom scales percent
#' @importFrom stringr str_c
#' @importFrom subfoldr save_plot
#' @importFrom tidyverse tidyverse_packages
#' @importFrom tmbr is.tmb_model
NULL
