pkg_list <- list(
  conflicted = c("conflicted"),
  rprofile = c(
    "devtools",
    "fledge",
    "lintr",
    "pkgdown",
    "remotes",
    "reprex",
    "rmarkdown",
    "roxygen2md",
    "styler",
    "testthat",
    "usethis"
  ),
  legacy = c("err", "rpdo", "plyr", "reshape2"),
  poisutils = c(
    "poisspatial",
    "poisdata",
    "poisix",
    "poisplot",
    "poisutils",
    "poispalette"
  ),
  bc = c(
    "bcdata",
    "renmods",
    "wqbc",
    "wqindex",
    "fishbc",
    "fwapgr",
    "fwatlasbc"
  ),
  canada = c("canwqdata", "ssdtools"),
  parallel = c("doFuture", "doParallel", "foreach", "future"),
  misc = c(
    "data.table",
    "daff",
    "naniar",
    "readwriteaws",
    "snakecase",
    "sessioninfo",
    "units",
    "yesno",
    "rsoi",
    "rtide",
    "tscbh",
    "tsdbr"
  ),
  spatial = c("mapview", "sf"),
  tidyverse_extras = c(
    "blob",
    "cli",
    "crayon",
    "hms",
    "glue",
    "lubridate",
    "magrittr",
    "pillar",
    "readxl",
    "rlang",
    "dm",
    "tidyplus",
    "broom"
  ),
  tidyverse_core = c(
    "ggplot2",
    "tibble",
    "tidyr",
    "readr",
    "purrr",
    "dplyr",
    "stringr",
    "forcats"
  ),
  plot = c(
    "grid",
    "ggdag",
    "DiagrammeR",
    "ggmap",
    "ggrepel",
    "ggspatial",
    "ggthemes",
    "ggh4x",
    "latex2exp",
    "scales",
    "viridis",
    "tinter"
  ),
  utils = c("chk", "dttr2", "hmstimer"),
  databasing = c("flobr", "dbflobr", "RSQLite", "readwritesqlite"),
  analysis = c(
    "universals",
    "extras",
    "term",
    "loo",
    "nlist",
    "newdata",
    "rescale",
    "mcmcr",
    "mcmcderive",
    "mcmcdata",
    "embr",
    "tmbr",
    "smbr2",
    "smbr",
    "jmbr",
    "priorsense",
    "sims",
    "ypr"
  ),
  reporting = c("knitr", "subfoldr2", "subfoldr2ext", "subreport")
)
