update_conflicted_code <- function() {
  prefs <- as.list(asNamespace("conflicted")$prefs, sorted = TRUE)

  name <- names(prefs)
  winner <- purrr::map_chr(prefs, 1)
  losers <- purrr::map_chr(purrr::map(prefs, -1), rlang::expr_deparse)

  code <- glue::glue('  conflicted::conflict_prefer("{name}", "{winner}", {losers}, quiet = TRUE)')
  text <- glue::glue('# Generated by update_conflicted_code(), do not edit by hand\nconflicts_fix <- function() {{\n{glue::glue_collapse(code, "\\n")}\n}}')
  writeLines(text, "R/conflicted.R")
  cli::cli_inform("Updated {.file R/conflicted.R}")
}

auto_update_conflicted_code <- function() {
  pkg_list_flat <- setdiff(
    c(
      rownames(installed.packages())[which(!is.na(installed.packages()[, "Priority"]))],
      unname(unlist(pkg_list))
    ),
    "tcltk"
  )
  conflicts <- conflicted::conflict_scout(rev(pkg_list_flat))

  name <- names(conflicts)
  winner <- purrr::map_chr(conflicts, 1)
  losers <- purrr::map(conflicts, -1)

  purrr::pwalk(list(name, winner, losers), conflicted::conflict_prefer)
  update_conflicted_code()
}
